#include "tsge/game_state/world_map_constants.hpp"

namespace tsge {

const std::array<CountryStaticData, 86> COUNTRY_STATIC_DATA = {
    {// USSR
     {CountryEnum::USSR,
      100,
      false,
      {CountryEnum::NORTH_KOREA, CountryEnum::AFGHANISTAN, CountryEnum::ROMANIA,
       CountryEnum::POLAND, CountryEnum::FINLAND},
      5,
      {Region::SPECIAL, Region::SPECIAL, Region::SPECIAL},
      1},

     // USA
     {CountryEnum::USA,
      100,
      false,
      {CountryEnum::MEXICO, CountryEnum::CANADA, CountryEnum::CUBA,
       CountryEnum::JAPAN, CountryEnum::USA},
      4,
      {Region::SPECIAL, Region::SPECIAL, Region::SPECIAL},
      1},

     // Central America
     {CountryEnum::MEXICO,
      2,
      true,
      {CountryEnum::USA, CountryEnum::GUATEMALA, CountryEnum::MEXICO,
       CountryEnum::MEXICO, CountryEnum::MEXICO},
      2,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::CUBA,
      3,
      true,
      {CountryEnum::NICARAGUA, CountryEnum::USA, CountryEnum::HAITI,
       CountryEnum::CUBA, CountryEnum::CUBA},
      3,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::GUATEMALA,
      1,
      false,
      {CountryEnum::MEXICO, CountryEnum::EL_SALVADOR, CountryEnum::HONDURAS,
       CountryEnum::GUATEMALA, CountryEnum::GUATEMALA},
      3,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::HONDURAS,
      2,
      false,
      {CountryEnum::GUATEMALA, CountryEnum::EL_SALVADOR, CountryEnum::NICARAGUA,
       CountryEnum::COSTA_RICA, CountryEnum::HONDURAS},
      4,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::EL_SALVADOR,
      1,
      false,
      {CountryEnum::GUATEMALA, CountryEnum::HONDURAS, CountryEnum::EL_SALVADOR,
       CountryEnum::EL_SALVADOR, CountryEnum::EL_SALVADOR},
      2,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::NICARAGUA,
      1,
      false,
      {CountryEnum::HONDURAS, CountryEnum::CUBA, CountryEnum::COSTA_RICA,
       CountryEnum::NICARAGUA, CountryEnum::NICARAGUA},
      3,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::COSTA_RICA,
      3,
      false,
      {CountryEnum::HONDURAS, CountryEnum::NICARAGUA, CountryEnum::PANAMA,
       CountryEnum::COSTA_RICA, CountryEnum::COSTA_RICA},
      3,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::PANAMA,
      2,
      true,
      {CountryEnum::COSTA_RICA, CountryEnum::COLOMBIA, CountryEnum::PANAMA,
       CountryEnum::PANAMA, CountryEnum::PANAMA},
      2,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::HAITI,
      1,
      false,
      {CountryEnum::CUBA, CountryEnum::DOMINICAN_REPUBLIC, CountryEnum::HAITI,
       CountryEnum::HAITI, CountryEnum::HAITI},
      2,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     {CountryEnum::DOMINICAN_REPUBLIC,
      1,
      false,
      {CountryEnum::HAITI, CountryEnum::DOMINICAN_REPUBLIC,
       CountryEnum::DOMINICAN_REPUBLIC, CountryEnum::DOMINICAN_REPUBLIC,
       CountryEnum::DOMINICAN_REPUBLIC},
      1,
      {Region::CENTRAL_AMERICA, Region::CENTRAL_AMERICA,
       Region::CENTRAL_AMERICA},
      1},

     // South America
     {CountryEnum::VENEZUELA,
      2,
      true,
      {CountryEnum::COLOMBIA, CountryEnum::BRAZIL, CountryEnum::VENEZUELA,
       CountryEnum::VENEZUELA, CountryEnum::VENEZUELA},
      2,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::COLOMBIA,
      1,
      false,
      {CountryEnum::VENEZUELA, CountryEnum::PANAMA, CountryEnum::ECUADOR,
       CountryEnum::COLOMBIA, CountryEnum::COLOMBIA},
      3,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::ECUADOR,
      2,
      false,
      {CountryEnum::COLOMBIA, CountryEnum::PERU, CountryEnum::ECUADOR,
       CountryEnum::ECUADOR, CountryEnum::ECUADOR},
      2,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::PERU,
      2,
      false,
      {CountryEnum::ECUADOR, CountryEnum::BOLIVIA, CountryEnum::CHILE,
       CountryEnum::PERU, CountryEnum::PERU},
      3,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::BOLIVIA,
      2,
      false,
      {CountryEnum::PERU, CountryEnum::PARAGUAY, CountryEnum::BOLIVIA,
       CountryEnum::BOLIVIA, CountryEnum::BOLIVIA},
      2,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::PARAGUAY,
      2,
      false,
      {CountryEnum::BOLIVIA, CountryEnum::URUGUAY, CountryEnum::ARGENTINA,
       CountryEnum::PARAGUAY, CountryEnum::PARAGUAY},
      3,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::CHILE,
      3,
      true,
      {CountryEnum::PERU, CountryEnum::ARGENTINA, CountryEnum::CHILE,
       CountryEnum::CHILE, CountryEnum::CHILE},
      2,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::URUGUAY,
      2,
      false,
      {CountryEnum::PARAGUAY, CountryEnum::ARGENTINA, CountryEnum::BRAZIL,
       CountryEnum::URUGUAY, CountryEnum::URUGUAY},
      3,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::ARGENTINA,
      2,
      true,
      {CountryEnum::PARAGUAY, CountryEnum::URUGUAY, CountryEnum::CHILE,
       CountryEnum::ARGENTINA, CountryEnum::ARGENTINA},
      3,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     {CountryEnum::BRAZIL,
      2,
      true,
      {CountryEnum::VENEZUELA, CountryEnum::URUGUAY, CountryEnum::BRAZIL,
       CountryEnum::BRAZIL, CountryEnum::BRAZIL},
      2,
      {Region::SOUTH_AMERICA, Region::SOUTH_AMERICA, Region::SOUTH_AMERICA},
      1},

     // Africa
     {CountryEnum::ALGERIA,
      2,
      true,
      {CountryEnum::TUNISIA, CountryEnum::MOROCCO, CountryEnum::FRANCE,
       CountryEnum::SAHARA_STATES, CountryEnum::ALGERIA},
      4,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::TUNISIA,
      2,
      false,
      {CountryEnum::ALGERIA, CountryEnum::LIBYA, CountryEnum::TUNISIA,
       CountryEnum::TUNISIA, CountryEnum::TUNISIA},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::MOROCCO,
      3,
      false,
      {CountryEnum::ALGERIA, CountryEnum::WEST_AFRICAN_STATES,
       CountryEnum::SPAIN, CountryEnum::MOROCCO, CountryEnum::MOROCCO},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::WEST_AFRICAN_STATES,
      2,
      false,
      {CountryEnum::MOROCCO, CountryEnum::IVORY_COAST,
       CountryEnum::WEST_AFRICAN_STATES, CountryEnum::WEST_AFRICAN_STATES,
       CountryEnum::WEST_AFRICAN_STATES},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::SAHARA_STATES,
      1,
      false,
      {CountryEnum::ALGERIA, CountryEnum::NIGERIA, CountryEnum::SAHARA_STATES,
       CountryEnum::SAHARA_STATES, CountryEnum::SAHARA_STATES},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::IVORY_COAST,
      2,
      false,
      {CountryEnum::WEST_AFRICAN_STATES, CountryEnum::NIGERIA,
       CountryEnum::IVORY_COAST, CountryEnum::IVORY_COAST,
       CountryEnum::IVORY_COAST},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::NIGERIA,
      1,
      true,
      {CountryEnum::SAHARA_STATES, CountryEnum::IVORY_COAST,
       CountryEnum::CAMEROON, CountryEnum::NIGERIA, CountryEnum::NIGERIA},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::CAMEROON,
      1,
      false,
      {CountryEnum::NIGERIA, CountryEnum::ZAIRE, CountryEnum::CAMEROON,
       CountryEnum::CAMEROON, CountryEnum::CAMEROON},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::ZAIRE,
      1,
      true,
      {CountryEnum::CAMEROON, CountryEnum::ANGOLA, CountryEnum::ZIMBABWE,
       CountryEnum::ZAIRE, CountryEnum::ZAIRE},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::ANGOLA,
      1,
      true,
      {CountryEnum::ZAIRE, CountryEnum::SOUTH_AFRICA, CountryEnum::BOTSWANA,
       CountryEnum::ANGOLA, CountryEnum::ANGOLA},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::SOUTH_AFRICA,
      3,
      true,
      {CountryEnum::ANGOLA, CountryEnum::BOTSWANA, CountryEnum::SOUTH_AFRICA,
       CountryEnum::SOUTH_AFRICA, CountryEnum::SOUTH_AFRICA},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::BOTSWANA,
      2,
      false,
      {CountryEnum::SOUTH_AFRICA, CountryEnum::ANGOLA, CountryEnum::ZIMBABWE,
       CountryEnum::BOTSWANA, CountryEnum::BOTSWANA},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::ZIMBABWE,
      1,
      false,
      {CountryEnum::ZAIRE, CountryEnum::BOTSWANA, CountryEnum::MOZAMBIQUE,
       CountryEnum::ZIMBABWE, CountryEnum::ZIMBABWE},
      3,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::MOZAMBIQUE,
      1,
      false,
      {CountryEnum::ZIMBABWE, CountryEnum::KENYA, CountryEnum::MOZAMBIQUE,
       CountryEnum::MOZAMBIQUE, CountryEnum::MOZAMBIQUE},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::KENYA,
      2,
      false,
      {CountryEnum::MOZAMBIQUE, CountryEnum::SOMALIA, CountryEnum::KENYA,
       CountryEnum::KENYA, CountryEnum::KENYA},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::ETHIOPIA,
      1,
      false,
      {CountryEnum::SOMALIA, CountryEnum::SUDAN, CountryEnum::ETHIOPIA,
       CountryEnum::ETHIOPIA, CountryEnum::ETHIOPIA},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::SUDAN,
      1,
      false,
      {CountryEnum::EGYPT, CountryEnum::ETHIOPIA, CountryEnum::SUDAN,
       CountryEnum::SUDAN, CountryEnum::SUDAN},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     {CountryEnum::SOMALIA,
      2,
      false,
      {CountryEnum::KENYA, CountryEnum::ETHIOPIA, CountryEnum::SOMALIA,
       CountryEnum::SOMALIA, CountryEnum::SOMALIA},
      2,
      {Region::AFRICA, Region::AFRICA, Region::AFRICA},
      1},

     // Middle East
     {CountryEnum::EGYPT,
      2,
      true,
      {CountryEnum::SUDAN, CountryEnum::LIBYA, CountryEnum::ISRAEL,
       CountryEnum::EGYPT, CountryEnum::EGYPT},
      3,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::LIBYA,
      2,
      true,
      {CountryEnum::TUNISIA, CountryEnum::EGYPT, CountryEnum::LIBYA,
       CountryEnum::LIBYA, CountryEnum::LIBYA},
      2,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::ISRAEL,
      4,
      true,
      {CountryEnum::EGYPT, CountryEnum::LEBANON, CountryEnum::SYRIA,
       CountryEnum::JORDAN, CountryEnum::ISRAEL},
      4,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::LEBANON,
      1,
      false,
      {CountryEnum::ISRAEL, CountryEnum::SYRIA, CountryEnum::JORDAN,
       CountryEnum::LEBANON, CountryEnum::LEBANON},
      3,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::SYRIA,
      2,
      false,
      {CountryEnum::LEBANON, CountryEnum::ISRAEL, CountryEnum::TURKEY,
       CountryEnum::SYRIA, CountryEnum::SYRIA},
      3,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::JORDAN,
      2,
      false,
      {CountryEnum::ISRAEL, CountryEnum::LEBANON, CountryEnum::IRAQ,
       CountryEnum::SAUDI_ARABIA, CountryEnum::JORDAN},
      4,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::IRAQ,
      3,
      true,
      {CountryEnum::JORDAN, CountryEnum::SAUDI_ARABIA, CountryEnum::IRAN,
       CountryEnum::GULF_STATES, CountryEnum::IRAQ},
      4,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::IRAN,
      2,
      true,
      {CountryEnum::IRAQ, CountryEnum::AFGHANISTAN, CountryEnum::PAKISTAN,
       CountryEnum::IRAN, CountryEnum::IRAN},
      3,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::SAUDI_ARABIA,
      3,
      true,
      {CountryEnum::GULF_STATES, CountryEnum::JORDAN, CountryEnum::IRAQ,
       CountryEnum::SAUDI_ARABIA, CountryEnum::SAUDI_ARABIA},
      3,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     {CountryEnum::GULF_STATES,
      3,
      false,
      {CountryEnum::SAUDI_ARABIA, CountryEnum::IRAQ, CountryEnum::GULF_STATES,
       CountryEnum::GULF_STATES, CountryEnum::GULF_STATES},
      2,
      {Region::MIDDLE_EAST, Region::MIDDLE_EAST, Region::MIDDLE_EAST},
      1},

     // Asia
     {CountryEnum::AFGHANISTAN,
      2,
      false,
      {CountryEnum::IRAN, CountryEnum::PAKISTAN, CountryEnum::USSR,
       CountryEnum::AFGHANISTAN, CountryEnum::AFGHANISTAN},
      3,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::PAKISTAN,
      2,
      true,
      {CountryEnum::AFGHANISTAN, CountryEnum::IRAN, CountryEnum::INDIA,
       CountryEnum::PAKISTAN, CountryEnum::PAKISTAN},
      3,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::INDIA,
      3,
      true,
      {CountryEnum::PAKISTAN, CountryEnum::BURMA, CountryEnum::INDIA,
       CountryEnum::INDIA, CountryEnum::INDIA},
      2,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::BURMA,
      2,
      false,
      {CountryEnum::INDIA, CountryEnum::LAOS, CountryEnum::BURMA,
       CountryEnum::BURMA, CountryEnum::BURMA},
      2,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::THAILAND,
      2,
      true,
      {CountryEnum::LAOS, CountryEnum::VIETNAM, CountryEnum::MALAYSIA,
       CountryEnum::THAILAND, CountryEnum::THAILAND},
      3,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::VIETNAM,
      1,
      false,
      {CountryEnum::THAILAND, CountryEnum::LAOS, CountryEnum::VIETNAM,
       CountryEnum::VIETNAM, CountryEnum::VIETNAM},
      2,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::LAOS,
      1,
      false,
      {CountryEnum::BURMA, CountryEnum::THAILAND, CountryEnum::VIETNAM,
       CountryEnum::LAOS, CountryEnum::LAOS},
      3,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::MALAYSIA,
      2,
      false,
      {CountryEnum::THAILAND, CountryEnum::INDONESIA, CountryEnum::AUSTRALIA,
       CountryEnum::MALAYSIA, CountryEnum::MALAYSIA},
      3,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::INDONESIA,
      1,
      false,
      {CountryEnum::MALAYSIA, CountryEnum::PHILIPPINES, CountryEnum::INDONESIA,
       CountryEnum::INDONESIA, CountryEnum::INDONESIA},
      2,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::PHILIPPINES,
      2,
      false,
      {CountryEnum::JAPAN, CountryEnum::INDONESIA, CountryEnum::PHILIPPINES,
       CountryEnum::PHILIPPINES, CountryEnum::PHILIPPINES},
      2,
      {Region::ASIA, Region::SOUTH_EAST_ASIA, Region::ASIA},
      2},

     {CountryEnum::JAPAN,
      4,
      true,
      {CountryEnum::SOUTH_KOREA, CountryEnum::TAIWAN, CountryEnum::PHILIPPINES,
       CountryEnum::USA, CountryEnum::JAPAN},
      4,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::SOUTH_KOREA,
      3,
      true,
      {CountryEnum::JAPAN, CountryEnum::TAIWAN, CountryEnum::NORTH_KOREA,
       CountryEnum::SOUTH_KOREA, CountryEnum::SOUTH_KOREA},
      3,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::NORTH_KOREA,
      3,
      true,
      {CountryEnum::SOUTH_KOREA, CountryEnum::USSR, CountryEnum::NORTH_KOREA,
       CountryEnum::NORTH_KOREA, CountryEnum::NORTH_KOREA},
      2,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::TAIWAN,
      3,
      false,
      {CountryEnum::SOUTH_KOREA, CountryEnum::JAPAN, CountryEnum::TAIWAN,
       CountryEnum::TAIWAN, CountryEnum::TAIWAN},
      2,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     {CountryEnum::AUSTRALIA,
      4,
      false,
      {CountryEnum::MALAYSIA, CountryEnum::AUSTRALIA, CountryEnum::AUSTRALIA,
       CountryEnum::AUSTRALIA, CountryEnum::AUSTRALIA},
      1,
      {Region::ASIA, Region::ASIA, Region::ASIA},
      1},

     // Europe
     {CountryEnum::POLAND,
      3,
      true,
      {CountryEnum::USSR, CountryEnum::CZECHOSLOVAKIA,
       CountryEnum::EAST_GERMANY, CountryEnum::POLAND, CountryEnum::POLAND},
      3,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::EAST_GERMANY,
      3,
      true,
      {CountryEnum::POLAND, CountryEnum::CZECHOSLOVAKIA,
       CountryEnum::WEST_GERMANY, CountryEnum::AUSTRIA,
       CountryEnum::EAST_GERMANY},
      4,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::CZECHOSLOVAKIA,
      3,
      false,
      {CountryEnum::POLAND, CountryEnum::EAST_GERMANY, CountryEnum::HUNGARY,
       CountryEnum::CZECHOSLOVAKIA, CountryEnum::CZECHOSLOVAKIA},
      3,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::HUNGARY,
      3,
      false,
      {CountryEnum::CZECHOSLOVAKIA, CountryEnum::ROMANIA,
       CountryEnum::YUGOSLAVIA, CountryEnum::AUSTRIA, CountryEnum::HUNGARY},
      4,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::ROMANIA,
      3,
      false,
      {CountryEnum::USSR, CountryEnum::HUNGARY, CountryEnum::YUGOSLAVIA,
       CountryEnum::TURKEY, CountryEnum::ROMANIA},
      4,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::BULGARIA,
      3,
      false,
      {CountryEnum::GREECE, CountryEnum::TURKEY, CountryEnum::BULGARIA,
       CountryEnum::BULGARIA, CountryEnum::BULGARIA},
      2,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::YUGOSLAVIA,
      3,
      false,
      {CountryEnum::ITALY, CountryEnum::GREECE, CountryEnum::HUNGARY,
       CountryEnum::ROMANIA, CountryEnum::YUGOSLAVIA},
      4,
      {Region::EUROPE, Region::EAST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::AUSTRIA,
      4,
      false,
      {CountryEnum::HUNGARY, CountryEnum::ITALY, CountryEnum::WEST_GERMANY,
       CountryEnum::EAST_GERMANY, CountryEnum::AUSTRIA},
      4,
      {Region::EUROPE, Region::EAST_EUROPE, Region::WEST_EUROPE},
      3},

     {CountryEnum::WEST_GERMANY,
      4,
      true,
      {CountryEnum::DENMARK, CountryEnum::EAST_GERMANY, CountryEnum::AUSTRIA,
       CountryEnum::BENELUX, CountryEnum::FRANCE},
      5,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::GREECE,
      2,
      false,
      {CountryEnum::ITALY, CountryEnum::YUGOSLAVIA, CountryEnum::BULGARIA,
       CountryEnum::TURKEY, CountryEnum::GREECE},
      4,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::TURKEY,
      2,
      false,
      {CountryEnum::ROMANIA, CountryEnum::BULGARIA, CountryEnum::GREECE,
       CountryEnum::SYRIA, CountryEnum::TURKEY},
      4,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::ITALY,
      2,
      true,
      {CountryEnum::SPAIN, CountryEnum::FRANCE, CountryEnum::YUGOSLAVIA,
       CountryEnum::GREECE, CountryEnum::AUSTRIA},
      5,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::FRANCE,
      3,
      true,
      {CountryEnum::SPAIN, CountryEnum::ITALY, CountryEnum::WEST_GERMANY,
       CountryEnum::UNITED_KINGDOM, CountryEnum::ALGERIA},
      5,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::SPAIN,
      2,
      false,
      {CountryEnum::MOROCCO, CountryEnum::FRANCE, CountryEnum::ITALY,
       CountryEnum::SPAIN, CountryEnum::SPAIN},
      3,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::BENELUX,
      3,
      false,
      {CountryEnum::UNITED_KINGDOM, CountryEnum::WEST_GERMANY,
       CountryEnum::BENELUX, CountryEnum::BENELUX, CountryEnum::BENELUX},
      2,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::UNITED_KINGDOM,
      5,
      false,
      {CountryEnum::FRANCE, CountryEnum::BENELUX, CountryEnum::CANADA,
       CountryEnum::NORWAY, CountryEnum::UNITED_KINGDOM},
      4,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::CANADA,
      4,
      false,
      {CountryEnum::USA, CountryEnum::UNITED_KINGDOM, CountryEnum::CANADA,
       CountryEnum::CANADA, CountryEnum::CANADA},
      2,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::NORWAY,
      4,
      false,
      {CountryEnum::UNITED_KINGDOM, CountryEnum::SWEDEN, CountryEnum::NORWAY,
       CountryEnum::NORWAY, CountryEnum::NORWAY},
      2,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::DENMARK,
      3,
      false,
      {CountryEnum::SWEDEN, CountryEnum::WEST_GERMANY, CountryEnum::DENMARK,
       CountryEnum::DENMARK, CountryEnum::DENMARK},
      2,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::SWEDEN,
      4,
      false,
      {CountryEnum::DENMARK, CountryEnum::NORWAY, CountryEnum::FINLAND,
       CountryEnum::SWEDEN, CountryEnum::SWEDEN},
      3,
      {Region::EUROPE, Region::WEST_EUROPE, Region::EUROPE},
      2},

     {CountryEnum::FINLAND,
      4,
      false,
      {CountryEnum::USSR, CountryEnum::SWEDEN, CountryEnum::FINLAND,
       CountryEnum::FINLAND, CountryEnum::FINLAND},
      2,
      {Region::EUROPE, Region::EAST_EUROPE, Region::WEST_EUROPE},
      3}}};

const std::array<InitialInfluenceData, 20> INITIAL_INFLUENCE_DATA = {
    {{CountryEnum::USSR, Side::USSR, 999},
     {CountryEnum::NORTH_KOREA, Side::USSR, 3},
     {CountryEnum::EAST_GERMANY, Side::USSR, 3},
     {CountryEnum::FINLAND, Side::USSR, 1},
     {CountryEnum::SYRIA, Side::USSR, 1},
     {CountryEnum::IRAQ, Side::USSR, 1},
     {CountryEnum::USA, Side::USA, 999},
     {CountryEnum::AUSTRALIA, Side::USA, 4},
     {CountryEnum::PHILIPPINES, Side::USA, 1},
     {CountryEnum::CANADA, Side::USA, 2},
     {CountryEnum::UNITED_KINGDOM, Side::USA, 5},
     {CountryEnum::PANAMA, Side::USA, 1},
     {CountryEnum::ISRAEL, Side::USA, 1},
     {CountryEnum::IRAN, Side::USA, 1},
     {CountryEnum::SOUTH_KOREA, Side::USA, 1},
     {CountryEnum::JAPAN, Side::USA, 1},
     {CountryEnum::SOUTH_AFRICA, Side::USA, 1}}};

}  // namespace tsge